enactjs/docs-utils

README.md, index.js, package.json
This PR updates a number of the standalone functions to be cleaner and more focused on a single task.  Also, added a little more info to the README.
=> PLAT-97902: Update to work with scanning extra repos

index.js
Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com
=> Adapt for non-standard mac find command

.eslintrc.js, index.js
Copy icons and don't copy `config.json` file.  Pass additional config data to docs.
=> Copy icons from theme config.json

index.js
Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com
=> Create static dir if needed

index.js
Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com
=> Improve see tag detection

package.json
Enact-DCO-1.0-Signed-off-by: Jeongran Jang jeongran.jang@lge.com
=> PLAT-120999: Update documentation version to 12.3.0

package.json
=> 0.3.3 release

index.js, package.json
For preventing malware issues, we need to update node modules that fix security vulnerabilities.
Update node modules' warnings via checking "npm audit"
WRN-11134
=> WRN-11134: fix security vulnerabilities

index.js, package-lock.json, package.json
After updating "readdirp" module version to "^3.6.0" a build error occured.
In order to fix I had to refactor the readdirp api call following this example: https://github.com/paulmillr/readdirp/tree/3.0.0
=> WRO-460: Docs-utils: "readdirp" module occurs build error

package-lock.json, package.json
Updated dependencies to the latest minor version.
Updated dependencies to the latest minor version.
WRP-7019
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong taeyoung.hong@lge.com
=> WRP-7019: Update package dependencies to fix security vulnerabilities

CHANGELOG.md, index.js, package-lock.json, package.json
Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com
Updated `mkdirp` dependency to latest version
Updated `mkdirp` dependency to the latest version
Replaced with new API: `mkdirp.mkdirpSync`
https://github.com/isaacs/node-mkdirp#mkdirpsyncdir-string-opts-mkdirpoptions--stringundefined
https://github.com/isaacs/node-mkdirp/blob/main/CHANGELOG.md
WRP-13729
=> WRP-13729: Update mkdirp to latest version

CHANGELOG.md, index.js, package-lock.json, package.json
Update jsonata dependency to latest version
Updated jsonata dependency to version 2.0.3.
WRP-13728
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-13728: Update jsonata dependency to latest version

package-lock.json, package.json
Updated dependencies to the latest minor version.
Updated dependencies to the latest minor version.
WRP-7017
=> WRP-7017: Update dependencies

package-lock.json, package.json
=> WRP-20604: Updated dependencies' minor version

package-lock.json, package.json
=> WRP-21914: Updated dependencies' minor version

package-lock.json, package.json
=> WRQ-415: Update minor dependencies to fix vulnerabilities

package-lock.json, package.json
=> WRQ-421: Update minor dependencies to fix vulnerabilities

package-lock.json, package.json
=> WRQ-13128: Update minor dependencies to fix vulnerabilities

package-lock.json, package.json
Updated dependencies' minor and patch version.
Updated dependencies'  minor and patch version.
WRR-10535
=> WRR-10535: Update dependencies' minor and patch version

package-lock.json, package.json
Update minor dependencies to fix vulnerabilities
Update minor dependencies to fix vulnerabilities
WRR-29513
=> WRR-29513: Update minor dependencies to fix vulnerabilities
